labels:
  platform: linux/amd64
when:
  - event: push
    branch: main
steps:
  - name: github-release
    image: oven/bun:1.3.14
    environment:
      GITHUB_API_TOKEN:
        from_secret: personal_access_tokens_fine_grained_tokens_jurislm
    commands:
      - bunx release-please github-release --token=$GITHUB_API_TOKEN --repo-url=https://github.com/jurislm/woodpecker-ci-plugin --target-branch=main --config-file=release-please-config.json --manifest-file=.release-please-manifest.json
  - name: release-pr
    image: oven/bun:1.3.14
    depends_on:
      - github-release
    environment:
      GITHUB_API_TOKEN:
        from_secret: personal_access_tokens_fine_grained_tokens_jurislm
    commands:
      - bunx release-please release-pr --token=$GITHUB_API_TOKEN --repo-url=https://github.com/jurislm/woodpecker-ci-plugin --target-branch=main --config-file=release-please-config.json --manifest-file=.release-please-manifest.json
